mode: ['eval_knn']
experiment_path: 'experiments/dino/2025-06-16_12_03_26'

dataset_name: 'stl10'
data_csv: 'training_data/stl10/train_labels.json'
data_dir: 'training_data/stl10/train_images'
num_classes: 10