type: 'dino_unsupervised'
student_temp: 0.1
teacher_temp: 0.04
teacher_momentum_start: 0.996
teacher_momentum_final: 1
num_all_views: 6
num_global_views: 2
num_epochs: 60
warmup_initial_learning_rate: 1e-6
warmup_final_learning_rate: 1e-3
batch_size: 96
resume_from_checkpoint: 'experiments/dino_unsupervised/2025-06-12_13_46_05/best_model.pth'