data:
  dataset_name: 'stl10'
  data_dir: 'training_data/stl10/unlabeled_images'
  val_split: 0.2
  num_workers: 4
  img_size: 192

model:
  patch_size: 16
  in_channels: 3 
  embed_dim: 384
  num_blocks: 6
  num_heads: 6
  mlp_dim: 1536
  dropout: 0.1
  output_dim: 65536
  center_momentum: 0.9
  teacher_momentum: 0.996

training:
  type: 'dino_unsupervised'
  student_temp: 0.1
  teacher_temp: 0.04
  num_all_views: 8
  num_global_views: 2
  random_seed: 42
  batch_size: 64
  num_epochs: 150
  warmup_initial_learning_rate: 1e-7
  warmup_final_learning_rate: 1e-4
  warmup_epochs: 10
  lr_final: 1e-6
  weight_decay: 0.001
  checkpoint_dir: './checkpoints'
  criterion:
    name: L1Loss
    params:
      reduction: mean
  optimizer:
    name: AdamW
    params:
      lr: ${training.warmup_initial_learning_rate}
      weight_decay: 0.05
  lr_scheduler:
    main:
      name: CosineAnnealingLR
      params:
        eta_min: 1e-6
    warmup:
      name: LinearWarmupScheduler
      params: {}

transforms:
  global_transform:
    - name: RandomResizedCrop 
      params:
        size: ${data.img_size}
        scale: [0.5, 1.0]
    - name: RandomHorizontalFlip
      params: {}
    - name: ToTensor

  local_transform:
    - name: RandomResizedCrop 
      params:
        size: ${data.img_size}
        scale: [0.05, 0.4]
    - name: RandomHorizontalFlip
      params: {}
    - name: ToTensor